# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q6U_uaizaS2hqY5sZ9HNAbFAW85zkYsi
"""

!pip install plotly --quiet

import os, sqlite3, warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    classification_report, roc_auc_score, roc_curve,
    ConfusionMatrixDisplay, mean_squared_error, r2_score
)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

sns.set_theme(style='whitegrid', palette='muted', font_scale=1.1)
plt.rcParams.update({'figure.dpi': 120,
                     'axes.spines.top': False,
                     'axes.spines.right': False})

PURPLE = '#534AB7'
TEAL   = '#1D9E75'
CORAL  = '#D85A30'
AMBER  = '#BA7517'
GRAY   = '#888780'
BLUE   = '#2471A3'

for folder in ['images_p1', 'images_p2', 'images_p3', 'data']:
    os.makedirs(folder, exist_ok=True)

print('✅ Global setup complete — all libraries loaded!')
print(f'   pandas {pd.__version__} | numpy {np.__version__}')

"""Load Data

"""

USE_REAL_DATA   = True
KAGGLE_FILENAME = '/content/Student Mental health.csv'

if USE_REAL_DATA:
    p1_raw = pd.read_csv('/content/Student Mental health.csv')
    print(f'✅ Real dataset loaded: {p1_raw.shape}')
else:
    print('ℹ️  Generating representative simulated data (same schema as Kaggle)...')
    np.random.seed(42)
    n = 101
    p1_raw = pd.DataFrame({
        'Timestamp'                                        : pd.date_range('2020-01-01', periods=n, freq='3D').astype(str),
        'Choose your gender'                               : np.random.choice(['Male','Female'], n, p=[0.35,0.65]),
        'Age'                                              : np.random.randint(18, 25, n),
        'What is your course?'                             : np.random.choice(['Engineering','BCS','BIT','Law','Accounting','Islamic Education'], n),
        'Your current year of Study'                       : np.random.choice(['Year 1','Year 2','Year 3','Year 4'], n),
        'What is your CGPA?'                               : np.round(np.random.uniform(2.0, 4.0, n), 2),
        'Marital status'                                   : np.random.choice(['Yes','No'], n, p=[0.1,0.9]),
        'Do you have Depression?'                          : np.random.choice(['Yes','No'], n, p=[0.35,0.65]),
        'Do you have Anxiety?'                             : np.random.choice(['Yes','No'], n, p=[0.45,0.55]),
        'Do you have Panic attack?'                        : np.random.choice(['Yes','No'], n, p=[0.3,0.7]),
        'Did you seek any specialist for a treatment?'     : np.random.choice(['Yes','No'], n, p=[0.25,0.75]),
        'Sleep quality'                                    : np.random.choice(['Poor','Average','Good'], n, p=[0.3,0.4,0.3]),
        'Study hours per day'                              : np.random.randint(1, 10, n),
    })
    p1_raw.loc[np.random.choice(n, 5, replace=False), 'What is your CGPA?'] = np.nan
    p1_raw.loc[np.random.choice(n, 3, replace=False), 'Sleep quality']       = np.nan

print(f'Shape: {p1_raw.shape[0]} rows × {p1_raw.shape[1]} columns')
p1_raw.head()

"""Profile the Data"""

print('━'*55)
print(f'  ROWS: {p1_raw.shape[0]}   |   COLUMNS: {p1_raw.shape[1]}')
print('━'*55)

profile = pd.DataFrame({
    'dtype'      : p1_raw.dtypes,
    'missing'    : p1_raw.isnull().sum(),
    'missing_%'  : (p1_raw.isnull().mean()*100).round(1),
    'unique'     : p1_raw.nunique(),
})
display(profile)

"""Data Cleaning"""

p1 = p1_raw.copy()

col_map = {
    'Choose your gender'                           : 'gender',
    'Age'                                          : 'age',
    'What is your course?'                         : 'course',
    'Your current year of Study'                   : 'current_year',
    'What is your CGPA?'                           : 'cgpa',
    'Marital status'                               : 'marital_status',
    'Do you have Depression?'                      : 'depression',
    'Do you have Anxiety?'                         : 'anxiety',
    'Do you have Panic attack?'                    : 'panic_attack',
    'Did you seek any specialist for a treatment?' : 'sought_treatment',
    'Timestamp'                                    : 'timestamp',
}


existing_cols_map = {old_name: new_name for old_name, new_name in col_map.items() if old_name in p1.columns}
p1.rename(columns=existing_cols_map, inplace=True)
p1.columns = p1.columns.str.strip().str.lower().str.replace(' ','_').str.replace('[^a-z0-9_]','',regex=True)

def convert_cgpa_to_numeric(cgpa_str):
    if pd.isna(cgpa_str):
        return np.nan
    cgpa_str = str(cgpa_str).replace(' ', '')
    if '–' in cgpa_str:
        start, end = map(float, cgpa_str.split('–'))
    elif '-' in cgpa_str:
        start, end = map(float, cgpa_str.split('-'))
    else:
        try:
            return float(cgpa_str)
        except ValueError:
            return np.nan
    return (start + end) / 2

p1['cgpa']          = p1['cgpa'].apply(convert_cgpa_to_numeric)
p1['cgpa']          = p1['cgpa'].fillna(p1['cgpa'].median())

p1['age']           = p1['age'].fillna(p1['age'].median())



for col in ['marital_status','depression','anxiety','panic_attack','sought_treatment']:
    p1[col] = p1[col].map({'Yes': 1, 'No': 0})

p1['current_year'] = p1['current_year'].astype(str).str.extract(r'(\d+)').astype(float)

p1['mh_burden']  = p1['depression'] + p1['anxiety'] + p1['panic_attack']
p1['cgpa_band']  = pd.cut(p1['cgpa'], bins=[0,2.49,2.99,3.49,4.01],
                           labels=['Below 2.5','2.5–2.99','3.0–3.49','3.5–4.0'])

print(f'Nulls remaining: {p1.isnull().sum().sum()}  ← must be 0')
print(f'Final shape: {p1.shape}')
display(p1.head())